services:
  email-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Main application port
      - "3001:3001" # OAuth callback port
    environment:
      - SQLITE_DB_PATH=/app/data/emails.db
      - PORT=${PORT:-3000}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - EMAIL_USER=${EMAIL_USER}
      - APP_URL=${APP_URL}
      - RESEND_USER=${RESEND_USER}
    volumes:
      - email-db-data:/app/data
    restart: unless-stopped

volumes:
  email-db-data:
